In [1]:
import numpy as np
from scipy.optimize import minimize
from IPython.display import Image

## trust region vs. gradient methods

## trust-ncg

- https://docs.scipy.org/doc/scipy/tutorial/optimize.html#trust-region-newton-conjugate-gradient-algorithm-method-trust-ncg

In [19]:
Image(url='../../imgs/trust-ncg.png', width=500)

In [2]:
from scipy.optimize import rosen_der, rosen_hess, rosen

## trust-ncg

In [11]:
def rosen_callback(xk):
    print(f"At iteration {rosen_callback.iteration}: x = {xk}, f(x) = {rosen(xk)}")
    rosen_callback.iteration += 1
rosen_callback.iteration = 0

In [12]:
x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])
res = minimize(rosen, x0, method='trust-ncg',
               jac=rosen_der, hess=rosen_hess,
               options={'gtol': 1e-8, 'disp': True}, callback=rosen_callback)

At iteration 0: x = [1.17182762 0.77097477 0.88495088 1.38139178 1.31986629], f(x) = 115.35713831787174
At iteration 1: x = [1.02230556 0.88234359 0.96636883 1.14568022 1.38212416], f(x) = 11.184281637491322
At iteration 2: x = [0.9525087  0.98617884 1.01287162 1.13437805 1.36754899], f(x) = 2.6342555416888764
At iteration 3: x = [1.01693959 1.03897616 1.08083267 1.16529887 1.33033595], f(x) = 0.11509992633210457
At iteration 4: x = [1.01835916 1.03862601 1.07958652 1.15598973 1.3344093 ], f(x) = 0.042233556159392144
At iteration 5: x = [1.01884444 1.03859274 1.07601568 1.15656231 1.33471556], f(x) = 0.03388062703252163
At iteration 6: x = [1.01857518 1.03686081 1.07458026 1.15518694 1.33534381], f(x) = 0.031514452913369996
At iteration 7: x = [1.01857518 1.03686081 1.07458026 1.15518694 1.33534381], f(x) = 0.031514452913369996
At iteration 8: x = [1.00788364 1.01367297 1.02930213 1.05892939 1.1105497 ], f(x) = 0.01701150089310485
At iteration 9: x = [1.00714813 1.01460472 1.02877689 1

In [7]:
res

 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 1.232595164407831e-30
       x: [ 1.000e+00  1.000e+00  1.000e+00  1.000e+00  1.000e+00]
     nit: 20
     jac: [-0.000e+00  0.000e+00  0.000e+00  4.441e-14 -2.220e-14]
    nfev: 21
    njev: 20
    nhev: 19
    hess: [[ 8.020e+02 -4.000e+02 ...  0.000e+00  0.000e+00]
           [-4.000e+02  1.002e+03 ...  0.000e+00  0.000e+00]
           ...
           [ 0.000e+00  0.000e+00 ...  1.002e+03 -4.000e+02]
           [ 0.000e+00  0.000e+00 ... -4.000e+02  2.000e+02]]

## dogleg

In [7]:
import scipy.optimize as so
x_iter = []

def callback(xk):
    x_iter.append(xk.copy())

x0 = np.array([10., 10])
rmax = 2.
r =.25
eta = 1./16
tol = 1e-5
opts = {'initial_trust_radius': r, 
        'max_trust_radius': 
        rmax, 'eta': eta, 
        'gtol': tol, 
        'disp': True}
sol1 = so.minimize(so.rosen, x0, method='dogleg', jac=so.rosen_der, hess=so.rosen_hess, options=opts, callback=callback)
sol1

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 32
         Function evaluations: 33
         Gradient evaluations: 31
         Hessian evaluations: 30


 message: Optimization terminated successfully.
 success: True
  status: 0
     fun: 2.7861938468014046e-18
       x: [ 1.000e+00  1.000e+00]
     nit: 32
     jac: [ 1.051e-08 -3.598e-09]
    nfev: 33
    njev: 31
    nhev: 30
    hess: [[ 8.020e+02 -4.000e+02]
           [-4.000e+02  2.000e+02]]